Added reading from stdin

diff --git a/grambo b/grambo
--- a/grambo
+++ b/grambo
@@ -9,64 +9,130 @@ echo "| Usage: grambo <galera node error log>                                   
 echo "|                                                                              |"
 echo "================================================================================"
 echo "  "
-if [ "$#" -ne 1 ]; then
-    echo "  "
-    echo "You have to provide the path to the MySQL/MariaDB Galera node error log."
-    echo "  "
-    echo "================================================================================"
-    echo "  "
-    echo "  "
-    exit
+#if [ "$#" -ne 1 ]; then
+#    echo "  "
+#    echo "You have to provide the path to the MySQL/MariaDB Galera node error log."
+#    echo "  "
+#    echo "================================================================================"
+#    echo "  "
+#    echo "  "
+#    exit
+#fi
+
+ReadStdin=0
+if [ $# -eq 0 ]; then
+	ReadStdin=1
+	Piped=$(</dev/stdin)
 fi
+
 echo " [MYSQL/MARIADB]"
 echo "--------------------------------------------------------------------------------"
-grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Version: "$2}'
-grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Socket: "$4}'
-grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Port: "$6}'
-grep ^Version $1 | sort | uniq | awk -F"wsrep_" '{print "[info] [server] Wsrep: "$2}'
+ if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep ^Version | sort | uniq | awk '{print "[info] [server] Version: "$2}'
+  	echo "$Piped" | grep ^Version | sort | uniq | awk '{print "[info] [server] Socket: "$4}'
+  	echo "$Piped" | grep ^Version | sort | uniq | awk '{print "[info] [server] Port: "$6}'
+  	echo "$Piped" | grep ^Version | sort | uniq | awk -F"wsrep_" '{print "[info] [server] Wsrep: "$2}'
+    else
+	grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Version: "$2}'
+  	grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Socket: "$4}'
+  	grep ^Version $1 | sort | uniq | awk '{print "[info] [server] Port: "$6}'
+  	grep ^Version $1 | sort | uniq | awk -F"wsrep_" '{print "[info] [server] Wsrep: "$2}'
+  fi
 echo "================================================================================"
 echo "  "
+
+
 echo " [GALERA]"
 echo "--------------------------------------------------------------------------------"
-grep -i "\[Note\] WSREP: " $1 | grep "listening at tcp"  |awk '{print $5}' | sort | uniq | awk -F"(" '{print $2}' | awk -F"," '{ print "[info] [galera] Node UUID: "$1}'
-grep -i "group uuid" $1 | sort | uniq | awk '{print "[info] [galera] Group UUID: "$4}' 
-grep "connecting to group" $1 | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Group name: "$1}'
-grep "connecting to group" $1 | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Peers: "$3}'
-grep "by Codership" $1 | awk -F"by Codership" '{print $1}' | awk '{print "[info] [galera] Version: "$7}' |sort | uniq 
-ip_address=$(grep -i "base_host" $1 | awk -F"base_host = " '{print $2}' | awk -F";" '{print $1}' | sort | uniq)
-echo "[info] [galera] Address: $ip_address"
-ipax=$ip_address
-grep -i "base_port" $1 | awk -F"base_port = " '{print $2}' | awk -F";" '{print "[info] [galera] Port: " $1}' | sort | uniq
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep -i "\[Note\] WSREP: " | grep "listening at tcp"  |awk '{print $5}' | sort | uniq | awk -F"(" '{print $2}' | awk -F"," '{ print "[info] [galera] Node UUID: "$1}'
+	echo "$Piped" | grep -i "group uuid" | sort | uniq | awk '{print "[info] [galera] Group UUID: "$4}' 
+	echo "$Piped" | grep "connecting to group" | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Group name: "$1}'
+	echo "$Piped" | grep "connecting to group" | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Peers: "$3}'
+	echo "$Piped" | grep "by Codership" | awk -F"by Codership" '{print $1}' | awk '{print "[info] [galera] Version: "$7}' |sort | uniq 
+	ip_address=$(echo "$Piped" | grep -i "base_host" | awk -F"base_host = " '{print $2}' | awk -F";" '{print $1}' | sort | uniq)
+	echo "$Piped" | grep -i "base_host" | awk -F"base_host = " '{print $2}' | awk -F";" '{print "[info] [galera] "$1}' | sort | uniq
+	#echo "[info] [galera] Address: $ip_address"
+	ipax=$ip_address
+	echo "$Piped" | grep -i "base_port" | awk -F"base_port = " '{print $2}' | awk -F";" '{print "[info] [galera] Port: " $1}' | sort | uniq
+    else
+	grep -i "\[Note\] WSREP: " $1 | grep "listening at tcp"  |awk '{print $5}' | sort | uniq | awk -F"(" '{print $2}' | awk -F"," '{ print "[info] [galera] Node UUID: "$1}'
+	grep -i "group uuid" $1 | sort | uniq | awk '{print "[info] [galera] Group UUID: "$4}' 
+	grep "connecting to group" $1 | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Group name: "$1}'
+	grep "connecting to group" $1 | awk -F"connecting to group" '{print $2}' | awk '{print "[info] [galera] Peers: "$3}'
+	grep "by Codership" $1 | awk -F"by Codership" '{print $1}' | awk '{print "[info] [galera] Version: "$7}' |sort | uniq 
+	ip_address=$(grep -i "base_host" $1 | awk -F"base_host = " '{print $2}' | awk -F";" '{print $1}' | sort | uniq)
+	echo "[info] [galera] Address: $ip_address"
+	ipax=$ip_address
+	grep -i "base_port" $1 | awk -F"base_port = " '{print $2}' | awk -F";" '{print "[info] [galera] Port: " $1}' | sort | uniq
+
+fi
+
 echo "================================================================================"
 echo "  "
 echo " [IST EVENTS]"
 echo "--------------------------------------------------------------------------------"
 #egrep "WSREP: IST request|WSREP: async IST sender starting|WSREP: async IST sender served" $1  | awk -v ipa=$ipax '{print ipa" 20"$0}' | awk '{print "[event] [ist] "$0}'
-egrep -i " ist " $1  | awk -v ipa=$ipax '{print ipa" 20"$0}' | awk '{print "[event] [ist] "$0}'
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | egrep -i " ist " | awk -v ipa=$ipax '{print ipa" 20"$0}' | awk '{print "[event] [ist] "$0}'
+else
+	egrep -i " ist " $1  | awk -v ipa=$ipax '{print ipa" 20"$0}' | awk '{print "[event] [ist] "$0}'
+fi
+
+
 echo "================================================================================"
 echo "  "
-echo " [SST EVENTS] #### TRICKY -> Currently RC=( \${PIPESTATUS[@]} ) is cut (if present) -- problem with ( as FS in awk"
+
+echo " [SST EVENTS] #### TRICKY -> Currently RC=( \${PIPESTATUS[@]} )  is cut (if present, or any other open parenthesis stuff before the timestamp) -- problem with ( as FS in awk"
 echo "--------------------------------------------------------------------------------"
-(grep "^WSREP_SST" $1  | awk -F'(' '{print $NF" "$1}' | awk -v ipa=$ipax -F') ' '{print ipa" "$1" "$2}' ;grep -i sst $1 | grep -v ^WSREP_SST  | awk -v ipa=$ipax '{print ipa" 20"$0}') | sort  | awk '{print "[event] [sst] "$0}'
+if [ $ReadStdin -eq 1 ]; then
+	(echo "$Piped" | grep "^WSREP_SST" | awk -F'(' '{print $NF" "$1}' | awk -v ipa=$ipax -F') ' '{print ipa" "$1" "$2}'; echo "$Piped" | grep -i sst | grep -v ^WSREP_SST  | awk -v ipa=$ipax '{print ipa" 20"$0}') | sort  | awk '{print "[event] [sst] "$0}'
+else
+	(grep "^WSREP_SST" $1  | awk -F'(' '{print $NF" "$1}' | awk -v ipa=$ipax -F') ' '{print ipa" "$1" "$2}' ;grep -i sst $1 | grep -v ^WSREP_SST  | awk -v ipa=$ipax '{print ipa" 20"$0}') | sort  | awk '{print "[event] [sst] "$0}'
+fi
 echo "================================================================================"
 echo "  "
+
 echo " [GCOMM EVENTS]"
 echo "--------------------------------------------------------------------------------"
-grep "WSREP: gcomm:" $1 | awk -v ipa=$ipax '{print ipa" 20"$0}'  | awk '{print "[event] [gco] "$0}'
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep "WSREP: gcomm:" | awk -v ipa=$ipax '{print ipa" 20"$0}'  | awk '{print "[event] [gco] "$0}'
+else
+	grep "WSREP: gcomm:" $1 | awk -v ipa=$ipax '{print ipa" 20"$0}'  | awk '{print "[event] [gco] "$0}'
+fi
 echo "================================================================================"
 echo "  "
+
 echo " [STATUS TRANSITIONS]"
 echo "--------------------------------------------------------------------------------"
-grep -hi SHIFTING $1 | awk -v ipa=$ipax '{print ipa" 20"$1" "$2" "$6"\t\t"$8}' | awk '{print "[event] [stt] "$0}'
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep -hi SHIFTING | awk -v ipa=$ipax '{print ipa" 20"$1" "$2" "$6"\t\t"$8}' | awk '{print "[event] [stt] "$0}'
+else
+	grep -hi SHIFTING $1 | awk -v ipa=$ipax '{print ipa" 20"$1" "$2" "$6"\t\t"$8}' | awk '{print "[event] [stt] "$0}'
+fi
 echo "================================================================================"
 echo "  "
+
 echo " [WARNINGS]"
 echo "--------------------------------------------------------------------------------"
-grep -i warning $1 | awk -v ipa=$ipax '{print "[event] [warning] "ipa" 20"$0}'
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep -i warning | awk -v ipa=$ipax '{print "[event] [warning] "ipa" 20"$0}'
+else
+	grep -i warning $1 | awk -v ipa=$ipax '{print "[event] [warning] "ipa" 20"$0}'
+fi
 echo "================================================================================"
 echo "  "
+
 echo " [ERRORS]"
 echo "--------------------------------------------------------------------------------"
-grep -i "error " $1 | awk -v ipa=$ipax '{print "[event] [error] "ipa" "$0}'
+if [ $ReadStdin -eq 1 ]; then
+	echo "$Piped" | grep -i "error " | awk -v ipa=$ipax '{print "[event] [error] "ipa" "$0}'
+else
+	grep -i "error " $1 | awk -v ipa=$ipax '{print "[event] [error] "ipa" "$0}'
+fi
 echo "================================================================================"
 echo "  "
+
+
+
+
